export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_ERROR = "FETCH_TASK_ERROR";

export const FILTER_TASK = "FILTER_TASK";
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const GET_EDITTING_TASK = "GET_EDITTING_TASK";

export const EDITTING_TASK = "EDITTING_TASK";
export const EDITTING_TASK_SUCCESS = "EDITTING_TASK_SUCCESS";
export const EDITTING_TASK_ERROR = "EDITTING_TASK_ERROR";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
